<?php
function ajaxtest_menu(){
    $items = array();
    $items['ajax-test'] = array(
        'title' => 'Ajax Test',
        'type' => MENU_NORMAL_ITEM,
        'page callback' => 'ajaxtest_page',
        'access argument' => array('access content')
    );
    $items['my-ajax-test/%'] = array(
        'title' => 'Ajax test callback',
        'type'  => MENU_CALLBACK,
        'page callback' => 'ajaxtest_callback',
        'page arguments' => array(1),
        'access arguments' => array('access content')
    );
    return $items;
}


function ajaxtest_page() {
    return array(
        '#type' => 'link',
        '#title' => t('Ajax Link'),
        '#href'  => 'my-ajax-test/nojs',
        '#prefix' => '<div id="ajax-link">',
        '#suffix' => '<div><div id="ajax-display"></div>',
        '#ajax' => array(
            'effect' => 'fade',
        ),
    );

}

function ajaxtest_callback($ajax){
    $time = t('The current time is: !time', array('!time' => date('Y-m-d H:i:s')));
    if ($ajax == 'ajax') {
        $commands = array();
        $commands[] = ajax_command_replace('#ajax-display', "<div id='ajax-display'>" . $time . "</div>");
        $commands[] = ajax_command_changed('#ajax-display');
        ajax_deliver(array('#type' => 'ajax', '#commands' => $commands));
    }
    else {
        return array(
            '#markup' => $time,
        );

    }
}
